# Generated by Django 3.2.3 on 2021-05-24 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_name', models.CharField(blank=True, default='', max_length=50)),
                ('expedition_id', models.CharField(blank=True, default='', max_length=50)),
                ('expedition_image', models.ImageField(default='', upload_to='images/')),
                ('description', models.TextField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeep_name', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('history', models.TextField(blank=True, default='', max_length=500)),
                ('specs', models.TextField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('subject', models.CharField(blank=True, default='', max_length=50)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('jeep_name', models.CharField(blank=True, default='', max_length=50)),
                ('expedition_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('portfolio_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('certification_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('introduction', models.TextField(blank=True, default='', max_length=500)),
                ('about', models.TextField(blank=True, default='', max_length=500)),
                ('education_1', models.TextField(blank=True, default='', max_length=500)),
                ('education_2', models.TextField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.TextField(blank=True, default='', max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expedition_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
