# Generated by Django 3.2.3 on 2021-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_pdf',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='resume_pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='certification_pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdfs/'),
        ),
    ]
