# Generated by Django 3.2.3 on 2021-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20210523_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='jeep_name',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
